---
title: "Type 2 diabetes and insulin resistance in three human metabolic tissues"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: sandstone
    orientation: columns
    vertical_layout: fill

runtime: shiny
  
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(ggplot2)
library(data.table)
# tags$head(includeHTML(("analytics.html")))
```

```{r, include = F}
library(GAlogger)
ga_set_tracking_id(as.character(read.table("BigBrotherCookie.txt", header = F)))
ga_set_approval(consent = TRUE)

ga_collect_pageview(page = "/main")

load("data/results.Rdata")

rank2logFC <- function(x, title = "", 
                       xZoom = c(NA, NA),
                       yZoom = c(NA, NA)){
  
  ggplot(x, mapping = aes(x = Rank, y = logFC, col = adj.P.Val)) +
    geom_point() +
    geom_hline(yintercept = 0, color = "gray") +
    scale_color_gradient(trans = "log", low = "darkred", high = "#502a57", 
                         breaks = c(0, 0.001, 0.05, 0.5)) +
    scale_shape(name = "Tissue") +
    xlab("Rank (high expression -> low expression)") + 
    ylab("logFC (IR/T2D vs NGT)") +
    coord_cartesian(xlim = xZoom, ylim = yZoom) +
    theme_bw() +
    theme(text = element_text(size = 14))
  
}

tissueComp <- function(gene){
  ggplot(dat[gene,], aes(x = Rank, y = logFC, shape = Tissue, col = adj.P.Val)) +
    geom_point(size = 5) +
    geom_hline(yintercept = 0, color = "black", lty = "dotted", size = 2) +
    geom_blank(data = data.frame(adj.P.Val = c(min(dat$adj.P.Val), 0.05, 1)), 
               aes(col = adj.P.Val), inherit.aes = F) +
    scale_color_gradient2(low = "red", mid = "darkred", high = "#502a57", midpoint = 0.05,
                          breaks = c(0, 0.001, 0.05, 0.1), 
                          limits = c(min(dat$adj.P.Val), 0.1)#midpoint = 0.05
    ) +
    scale_shape_manual(name = "Tissue",  values = c(adipose = "circle",
                                                    beta = "triangle",
                                                    skeletal = "square")) +
    theme_bw() +
    theme(text = element_text(size = 16),
          strip.text = element_text(size = 18), ) +
    ylab("logFC (IR/T2D vs NGT)") +
    facet_wrap(~Symbol) 
}

```

Column {.tabset data-width=150}
--------------------------------------------------

### Search

Select points on plot to \n visualize genes across tissues.  

Click on selection to zoom in,  double-click to zoom out.  

Manually search for gene(s) \n in the box:  

```{r}
#necessary for speed
ui <- fluidRow(selectizeInput(inputId = "gene", 
                              choices = NULL, 
                              multiple = T, 
                              label = ""),
               width = 1)

server <- function(input, output){
  updateSelectizeInput(inputId = "gene", 
                    choices = unique(dat$Symbol), 
                    server = TRUE)
  observeEvent(input$gene, {
    gene$gene <- input$gene
  })
}
shinyApp(ui = ui, server = server)
```

### About this dashboard

This dashboard aims to allow researcherers to quickly explore questions and test ideas about transcriptomics and whole body physiology. It visualizes the gene experssion and log fold change between Type 2 Diabetics (or insulin resistant) and Normal Glucose Tolerant human volunteers in three metabolically important tissues: adipose tissue, skeletal muscle and beta cells.

**A small word of caution: the three tissues compared are analyzed on different transcriptomic platforms. Lack of gene quantification in any one tissue should not be taken to mean absence of expression. Moreover, as this data is from three different studies, the cohorts are different along with any batch effects that this entails. The three studies were selected based on cohort size, and were reanalyzed (but not pre-proccessed) using the same pipeline (limma).**

The data is from the public domain [[1](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE40234), [2](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE18732), [3](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE76894)], and the analysis code can be found [here](https://leonidaslundell.github.io/).


```{r}
n <- t(n)
rownames(n) <- c("Adipose tissue", "Beta cell", "Skeletal muscle")
knitr::kable(n, caption = "Number of participants")
```

Column {data-width=400}
--------------------------------------------------

### Adipose tissue

```{r}
plotOutput("adiposePlot", brush = "adiposeBrush", click = "adiposeZoomIn", dblclick = "adiposeZoomOut")

rangesAdipose <- reactiveValues(x = NULL, y = NULL)

output$adiposePlot <- renderPlot(
    rank2logFC(dat[Tissue == "adipose"&abs(logFC)>.32,], 
               xZoom = rangesAdipose$x,
               yZoom = rangesAdipose$y,
               "adipose tissue")
  )

observeEvent(input$adiposeZoomIn, {
  ga_collect_event(event_category = "Plot manipulation", event_action = "Zooming in")
  if(!is.null(input$adiposeBrush)){
    rangesAdipose$x <- c(input$adiposeBrush$xmin, input$adiposeBrush$xmax)
    rangesAdipose$y <- c(input$adiposeBrush$ymin, input$adiposeBrush$ymax) 
  }
})
observeEvent(input$adiposeZoomOut, {
  ga_collect_event(event_category = "Plot manipulation", event_action = "Zooming out")
  rangesAdipose$x <- c(NA, NA)
  rangesAdipose$y <- c(NA, NA)
})
```

### Beta cell

```{r}
plotOutput("betaPlot", brush = "betaBrush", click = "betaZoomIn", dblclick = "betaZoomOut")

rangesBeta <- reactiveValues(x = NULL, y = NULL)

output$betaPlot <- renderPlot(
    rank2logFC(dat[Tissue == "beta"&abs(logFC)>.32,], 
               xZoom = rangesBeta$x,
               yZoom = rangesBeta$y,
               "beta tissue")
  )

observeEvent(input$betaZoomIn, {
  ga_collect_event(event_category = "Plot manipulation", event_action = "Zooming in")
  if(!is.null(input$betaBrush)){
    rangesBeta$x <- c(input$betaBrush$xmin, input$betaBrush$xmax)
    rangesBeta$y <- c(input$betaBrush$ymin, input$betaBrush$ymax) 
  }
})
observeEvent(input$betaZoomOut, {
  ga_collect_event(event_category = "Plot manipulation", event_action = "Zooming out")
  rangesBeta$x <- c(NA, NA)
  rangesBeta$y <- c(NA, NA)
})
```

### Skeletal muscle

```{r}
plotOutput("skeletalPlot", brush = "skeletalBrush", click = "skeletalZoomIn", dblclick = "skeletalZoomOut")

rangesSkeletal <- reactiveValues(x = NULL, y = NULL)

output$skeletalPlot <- renderPlot(
    rank2logFC(dat[Tissue == "skeletal"&abs(logFC)>.32,], 
               xZoom = rangesSkeletal$x,
               yZoom = rangesSkeletal$y,
               "skeletal tissue")
  )

observeEvent(input$skeletalZoomIn, {
  if(!is.null(input$skeletalBrush)){
    rangesSkeletal$x <- c(input$skeletalBrush$xmin, input$skeletalBrush$xmax)
    rangesSkeletal$y <- c(input$skeletalBrush$ymin, input$skeletalBrush$ymax) 
  }
})
observeEvent(input$skeletalZoomOut, {
  ga_collect_event(event_category = "Plot manipulation", event_action = "Zooming out")
  rangesSkeletal$x <- c(NA, NA)
  rangesSkeletal$y <- c(NA, NA)
})
```

Column {data-width=600}
--------------------------------------------------

```{r}
gene <- reactiveValues(gene = "SLC2A4")

observeEvent(input$gene, {
  ga_collect_event(event_category = "Gene input", event_action = "typed gene")
  gene$gene <- input$gene
})

observeEvent(c(input$skeletalBrush,
               input$betaBrush,
               input$adiposeBrush),{
                 temp <- c(
                   brushedPoints(dat[Tissue == "adipose" & abs(logFC)>.32,], 
                                 input$adiposeBrush, "Rank", "logFC")$Symbol,
                   brushedPoints(dat[Tissue == "beta" & abs(logFC)>.32,], 
                                 input$betaBrush, "Rank", "logFC")$Symbol,
                   brushedPoints(dat[Tissue == "skeletal" & abs(logFC)>.32,], 
                                 input$skeletalBrush, "Rank", "logFC")$Symbol)
                 gene$gene <- temp
               })

observeEvent(gene$gene, {
  print(gene$gene)
  if(length(gene$gene)>10){
    ga_collect_event(event_category = "Gene input", event_action = "Brushed too many genes")
    temp <- ggplot(data.frame(x = 1, y = 1, label = "Too many genes to visualize"), 
                   aes(x,y,label = label)) + geom_text() + theme_void()
    output$genes <- renderPlot(temp)
  }else{
    if(length(gene$gene)==0){
      temp <- ggplot(data.frame(x = 1, y = 1, label = "Select interesting genes from from the plots"), 
                   aes(x,y,label = label)) + geom_text() + theme_void()
      output$genes <- renderPlot(temp)
    }else{
      ga_collect_event(event_category = "Gene input", event_action = "Brushed less than 10 genes")
      output$genes <- renderPlot(tissueComp(as.character(gene$gene)))
    }
  }
})
```

### Comparing genes across tissues

```{r}
plotOutput("genes")
```

### Table

```{r}
renderDataTable(dat[Symbol %in% gene$gene, c("Symbol", 
                                             "Tissue", 
                                             "logFC", 
                                             "adj.P.Val", 
                                             "Rank")][order(Symbol)],
                options = list(paginate = FALSE,
                               dom = 't'))
```

